input {
  file {
    path => "/cowrie/var/log/cowrie/cowrie.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}


output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    index => "cowrie-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "eB7mvZHMsD1cq3Qc6Fju"
    ssl_enabled => true
    ssl_verification_mode => "none"
  }

  stdout { codec => rubydebug }
}

